name:    PianoMusicGeneratorWebApp
version: "0.0.0"

dependencies:
- base
- yesod-core
- yesod-static
- base >= 4.7 && < 5
- Euterpea
- yesod
- text
- random

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  PianoMusicGeneratorWebApp:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PianoMusicGeneratorWebApp
    - base >= 4.7 && < 5
    - yesod
    - text
    - random
